Update first-flag.mdx
launchdarkly/LaunchDarkly-Docs pull request #162
Opened 2021-05-26 17:45 UTC by leobyeon

wanted to make it clearer that flags exist across **all** environments within a project—not just that it can. it always does

2021-05-26 19:37 UTC, ember-stevens commented on src/content/topics/guides/tutorials/first-flag.mdx
> +The basic unit of work in LaunchDarkly is a **feature flag**, often referred to as a **flag**. Flags exist inside LaunchDarkly **environments**, and across multiple environments. All the environments
```suggestion
The basic unit of work in LaunchDarkly is a **feature flag**, often referred to as a **flag**. Flags exist inside **environments**. All the environments in your LaunchDarkly instance are referred to as your LaunchDarkly **project**. A project can contain multiple environments, and flags exist across all environments within a project.
```
I actually like your explanation text better.

2021-05-26 19:55 UTC, ember-stevens requested changes
I like your wording better.

2021-05-27 22:35 UTC, leobyeon commented
Ah yeah, I guess that is clearer. Good point!

2021-05-27 22:41 UTC, ember-stevens approved these changes

2021-05-27 23:24 UTC, merged