Update environment creation document
launchdarkly/LaunchDarkly-Docs pull request #250
Opened 2022-03-10 20:44 UTC by mguoynes

2022-03-11 21:24 UTC, mmrj requested changes
Thanks for putting this together! I added some minor copyedits. 

When would you like this published?

2022-03-11 21:24 UTC, mmrj commented on src/content/topics/home/organizing-flags/environments.mdx
> +3. Navigate to the selected project by clicking on the **Project** link.
```suggestion
3. Navigate to the selected project by clicking the name of the project.
```

2022-03-11 21:24 UTC, mmrj commented on src/content/topics/home/organizing-flags/environments.mdx
> +3. In the **Projects** results click on a project name to navigate to that project.
```suggestion
3. Navigate to the selected project by clicking the name of the project.
```
If I'm following correctly, this step is the same as what you're doing in environments.mdx/line 36. Is that right? If so, let's use the same language.

2022-03-11 21:24 UTC, mmrj commented on src/content/topics/home/organizing-flags/environments.mdx
> +3. In the **Projects** results click on a project name to navigate to that project.
```suggestion
3. Navigate to the selected project by clicking the name of the project.
```
Same comment as above, I think we can standardize the language here.

2022-03-11 21:24 UTC, mmrj commented on src/content/topics/home/organizing-flags/environments.mdx
> +6. Enter a value in the **TTL input** and once done click **Save Environment**.
```suggestion
6. Enter a value in the **TTL input** and click **Save environment**.
```

2022-03-11 21:36 UTC, ember-stevens commented on src/content/topics/home/organizing-flags/environments.mdx
> +5. Select "Edit environment." An "Edit environment" panel appears.
```suggestion
5. Select "Edit environment." The "Edit environment" panel appears.
```

2022-03-11 21:36 UTC, ember-stevens commented on src/content/topics/home/organizing-flags/environments.mdx
> +5. Select "Edit environment." An "Edit environment" panel appears.
```suggestion
5. Select "Edit environment." The "Edit environment" panel appears.
```

2022-03-14 13:47 UTC, mguoynes commented
work in progress..

> Thanks for putting this together! I added some minor copyedits.
> 
> When would you like this published?

It will be a bit, the project isn't completed yet. Once we finish up, would you like me to reach out?

2022-03-14 16:44 UTC, mmrj commented
> work in progress..
> 
> > Thanks for putting this together! I added some minor copyedits.
> > When would you like this published?
> 
> It will be a bit, the project isn't completed yet. Once we finish up, would you like me to reach out?

Yes please! We can merge & publish once the implementation is ready to be released. Thanks so much.

2022-03-28 18:01 UTC, closed without merging