clarify that the user must be a hash in ruby
launchdarkly/LaunchDarkly-Docs pull request #275
Opened 2022-06-16 22:48 UTC by Oneill38

While setting up the LD ruby client myself I was confused by the ruby example: `value = client.variation("your.feature.key", user, false)` because it seemed that `user` was an object. After some trial and error, and looking at the [ruby sdk docs](https://launchdarkly.github.io/ruby-server-sdk/LaunchDarkly/LDClient.html#variation-instance_method), I realized it actually needs to be a hash, and that the `key:` keyword was required. I'm updating this so that hopefully other folks are less confused in the future

2022-06-27 19:07 UTC, eli-darkly requested changes
I don't think this is quite the right way to go.

The basic concern here, if I understand correctly, is that it was unclear that a user in the Ruby SDK is a hash. That is, it was unclear on _this_ page; it is stated clearly in the Ruby SDK API docs for the [variation](https://launchdarkly.github.io/ruby-server-sdk/LaunchDarkly/LDClient.html#variation-instance_method) method, and also in the Ruby SDK section of our general docs on [user configuration](https://docs.launchdarkly.com/sdk/features/user-config#ruby). The latter goes into quite a bit of detail, so I think a better way to clarify this section would be to edit line 813 to say:

```
`variation` calls take the feature flag key, a user hash (see
[User configuration](/sdk/features/user-config#ruby)), and a
default value.
```

I would prefer not to show something like `{ key: user.id }` in the example code for several reasons:

1. It's inconsistent with all of the other server-side code examples, which assume that `user` is a user object of the correct type that the application has already constructed. The point of this page is to show how to call `variation`; how to construct a user is what the "User configuration" page is for.
2. When people see an expression like `{ key: user.id }`, they are likely to take it literally and think that `key` is the only property they want, or that there is supposed to be some other kind of `user` object that has an `id` property.

2022-06-27 19:39 UTC, Oneill38 commented
> That is, it was unclear on this page

That's correct, it was unclear on this page. I was looking at this page in the docs in particular for how to setup a working example on how to evaluate a flag. I do think linking the user configuration docs would be helpful here. I disagree with the points raised for not showing something like `{ key: user.id }`, or a similar example for the following reasons:

1. Just because all the other server side examples are not currently providing an example for user doesn't mean that's the most correct/useful option to the end user looking to integrate for the first time. 

2. If I'm navigating to a docs page about how to set up a variation, as the user I'd like an example that clearly states how to do that. User is a required argument, I don't think it's unreasonable to want an example of the actual required arguments. 

> When people see an expression like { key: user.id }, they are likely to take it literally and think that key is the only property they want, or that there is supposed to be some other kind of user object that has an id property.

By this logic then the example on page https://docs.launchdarkly.com/sdk/server-side/ruby shouldn't exist. In reality the example on that page is actually extremely helpful and gave me the idea in the first place that a user must be a hash. It never made me assume that `key` must be an email, or that it was the only attribute that could be passed.

2022-06-27 19:47 UTC, eli-darkly commented
@Oneill38, I'm going to defer to the documentation team who will also review this PR. There are many code examples in our docs, and people have many different ideas about what they'd like code examples to look like. The only thing I feel strongly about in this case is that 1. there should be a link to the docs that are more specifically about users, and 2. I do not think we should write something like `user.id` because it could easily give the impression that people are supposed to have an `id` property somewhere.

However, I'd also like to stress that we do not intend for these feature pages to be the _only_ reference people use to find out how to write code with the SDKs. For all questions like "what are the parameters to this method and what types are they", the source of truth is always the SDK API docs, which are the first link on the Ruby SDK page.

2022-07-01 18:28 UTC, scribblingfox commented
Hi @Oneill38! Thanks so much for the PR and conversation with Eli. We're updating these docs to indicate this is a user *hash* and adding a link to the user config docs. 

Your PR prompted a discussion within the docs team about how effectively the information in our SDK docs is organized. We may make further updates based on your feedback. Unfortunately, those team discussions take place in LaunchDarkly-specific tools, so you won't be able to follow along live, but we appreciate your thoughtful suggestions! Thanks very much for the PR!

2022-07-01 19:07 UTC, scribblingfox commented
Docs update tracked in our changelog: https://docs.launchdarkly.com/home/changelog

2022-07-01 19:07 UTC, closed without merging