Update managing.mdx
launchdarkly/LaunchDarkly-Docs pull request #89
Opened 2020-09-24 16:27 UTC by mira-cho

Adding actions to filter table

2020-09-24 16:40 UTC, bwoskow-ld requested changes

2020-09-24 16:40 UTC, bwoskow-ld commented on src/content/topics/integrations/Slack/managing.mdx
> +      <TableCell>Tag</TableCell>
Ideally these would be in the same order as they're displayed in the app: https://monosnap.com/direct/fFGOcJpyjOl417Gg1ztmMVvTyfCjCF (meaning, move "Tag" down to the bottom). Also rename "Tag" to "Flag tag" and update the description; we don't support other kinds of tags such as segment tags.

2020-09-24 21:01 UTC, bwoskow-ld approved these changes

2020-09-30 19:37 UTC, mira-cho reviewed
i think this all looks good to go, and had the same thought about table order, although i remain naive about how to preview it in final form

2020-10-01 16:05 UTC, merged