Update notifications.mdx
launchdarkly/LaunchDarkly-Docs pull request #91
Opened 2020-09-25 17:30 UTC by mira-cho

instructions for filtering on ready to remove

2020-09-25 17:37 UTC, bwoskow-ld requested changes

2020-09-25 17:37 UTC, bwoskow-ld commented on src/content/topics/integrations/Slack/notifications.mdx
> +This topic explains how to subscribe to flag notifications in Slack channels. You can receive notifications for when flags are created, updating, deleted, or ready for removal.
```suggestion
This topic explains how to subscribe to flag notifications in Slack channels. You can receive notifications for when flags are created, updated, deleted, or ready for removal.
```

2020-09-25 17:37 UTC, bwoskow-ld commented on src/content/topics/integrations/Slack/notifications.mdx
> +In the slack app, you can subscribe to notifications when it’s time to remove flags from code. Removing from code is a necessary step before archiving flags.
```suggestion
In the Slack app, you can subscribe to notifications when it’s time to remove flags from code. Removing from code is a necessary step before archiving flags.
```

2020-09-25 17:37 UTC, bwoskow-ld commented on src/content/topics/integrations/Slack/notifications.mdx
> +Read about [deleting and archiving flags](https://docs.launchdarkly.com/home/managing-flags/flag-archive-delete) to learn how to keep your codebase clean. The Slack app makes it easy to receive notif
```suggestion
Read about [deleting and archiving flags](https://docs.launchdarkly.com/home/managing-flags/flag-archive-delete) to learn how to keep your code base clean. The Slack app makes it easy to receive notifications once flags are ready to remove.
```

2020-09-25 17:37 UTC, bwoskow-ld commented on src/content/topics/integrations/Slack/notifications.mdx
> +2. Type `/launchdarkly susbcribe`and press **Enter**. The filter modal appears.
```suggestion
2. Type `/launchdarkly subscribe` and press **Enter**. The filter modal appears.
```

2020-09-25 17:37 UTC, bwoskow-ld commented on src/content/topics/integrations/Slack/notifications.mdx
> +1. Open the channel where you want to get notifcations on flags that are ready to remove.
```suggestion
1. Open the channel where you want to get notifications on flags that are ready to remove.
```

2020-09-25 17:37 UTC, bwoskow-ld commented on src/content/topics/integrations/Slack/notifications.mdx
> +4. Select "Ready for removal" from the Actions dropdown, which lets you only be notified on flags that are ready to remove and archive.
```suggestion
4. Select "Ready for removal" from the **Actions** dropdown, which lets you only be notified on flags that are ready to remove and archive.
```

2020-09-25 17:37 UTC, bwoskow-ld commented on src/content/topics/integrations/Slack/notifications.mdx
> +6. Click **Add flag to Channel** in the dropdown menu next to the flag you wish to subscribe to, or, click **Add filter to channel** if you want all of the results to show notifications.
```suggestion
6. Click **Add flag to channel** in the dropdown menu next to the flag you wish to subscribe to, or, click **Add filter to channel** if you want all of the results to show notifications.
```

2020-09-25 17:37 UTC, bwoskow-ld commented on src/content/topics/integrations/Slack/notifications.mdx
> +5. Click **Filter**
```suggestion
5. Click **Filter**.
```

2020-09-25 17:37 UTC, bwoskow-ld commented on src/content/topics/integrations/Slack/notifications.mdx
> +3. Filter on the flag, project, environment, or tags where you want to be notified when flags have become "inactive" or "launched".
```suggestion
3. Filter on the project, environment, flag key, or flag tags where you want to be notified when flags have become "inactive" or "launched".
```

2020-09-25 17:37 UTC, bwoskow-ld commented on src/content/topics/integrations/Slack/notifications.mdx
> +7. You'll see a notification that your selections, along with the Action "ready for removal" has been added to the channel.
```suggestion
7. You'll see a notification that your subscription has been added to the channel.
```

2020-09-30 17:41 UTC, mira-cho commented on src/content/topics/integrations/Slack/notifications.mdx
> +This topic explains how to subscribe to flag notifications in Slack channels. You can receive notifications for when flags are created, updating, deleted, or ready for removal.
nice fix

2020-09-30 20:50 UTC, bwoskow-ld commented on src/content/topics/integrations/Slack/notifications.mdx
> +5. Click **Filter**
Minor, but I unresolved this -- I do think we should add punctuation since this is a (short yet) complete sentence.

2020-10-01 16:07 UTC, scribblingfox approved these changes

2020-10-01 16:07 UTC, merged